CREATE TABLE IF NOT EXISTS HELP_CATEGORY
(
   ID INT AUTO_INCREMENT PRIMARY KEY,
   CATEGORY_NAME VARCHAR (250) NOT NULL
);


CREATE TABLE IF NOT EXISTS HELP_FAQ
(
   ID INT AUTO_INCREMENT PRIMARY KEY,
   CATEGORY_ID INT NULL,
   QUESTION VARCHAR (1000) NOT NULL,
   ANSWER VARCHAR (4000) NOT NULL
);
